### ISSUE TITLE
External storage problem

### ISSUE THREAD

**Issue by gabest11** [hippie68/ftpdump#10]
dump_and_extract_pkg "$root/user/app/$title_id/app.pkg"
dump_and_extract_pkg "$root/user/patch/$title_id/patch.pkg"

I think these two lines have the path hard coded. The pkg files can be found at /mnt/ext0/user/app/CUSA* (or ../patch/..).

**Comment by hippie68** [comment]
Thank you for reporting this. Please test this updated script version and tell me if it fixes the problem: 
[ftpdump.zip](https://github.com/hippie68/ftpdump/files/7775036/ftpdump.zip)

**Comment by gabest11** [comment]
It's working now. I just replaced the path temporarily, but this one also checks for existing files over ftp. Nicely done. I'm not a bash script guy :)
