### ISSUE TITLE
Cannot connect to ftp server

### ISSUE THREAD

**Issue by nthnplks21** [hippie68/ftpdump#12]
My ftp works fine I'm able to access it through WinSCP, windows explorer and remote package installer but I keep getting this error

Could not connect to FTP server. Is it running, and are IP address and port correct?
Error encountered, script aborted.

I've tried putting the IP and port in command as well as the bash file with no luck, I also tried Ethernet and wifi

I've tried using the FTP payload hosted on karp218.ir as well as the one included with goldhen

**Comment by hippie68** [comment]
Something may be blocking your WSL's network connection. Make sure you have local network access from within WSL. To verify, I'd open WSL and type:

    ifconfig
    ping google.com
