### ISSUE TITLE
script failing to download unencrypted npbind and nptitle

### ISSUE THREAD

**Issue by Masamune3210** [hippie68/ftpdump#16]
Script works fine but recently it has seemingly started to fail to download the unencrypted versions of npbind.dat and nptitle.dat. It gets the encrypted version instead. Its not a issue with the FTP binary i don't think, as i can manually go to the path that the script claims its pulling from and the file is unencrypted but what ends up in the dumped folder is the encrypted version instead

**Comment by Masamune3210** [comment]
Actually just noticed that my ftp program is set to use goldhen's FTP vs yours while the script is using yours, so it may actually be a issue with the FTP server after all

**Comment by Masamune3210** [comment]
yeah, that explains a lot of things, Ill remove resume for now, thanks! love the script btw, makes everything super easy

**Comment by hippie68** [comment]
The current script that I attached here https://github.com/hippie68/ftpdump/issues/8#issuecomment-1033237938 is supposed to fix that bug. I'm waiting for user feedback currently before releasing it.

**Comment by Masamune3210** [comment]
Ill try the fixed script with my next dump

**Comment by hippie68** [comment]
Apologies, it turned out the previously attached file was not working correctly. The current version is here: https://github.com/hippie68/ftpdump/files/8033988/ftpdump.zip

**Comment by Masamune3210** [comment]
Alright I'll switch it out and let you know if everything dumps correctly, does the dump method matter? I'm using the --use-pfs flag

**Comment by hippie68** [comment]
It should make no difference.

**Comment by hippie68** [comment]
If you mean the debug messages, "dirent" stands for "directory entry".

**Comment by Masamune3210** [comment]
ok, my bad lol

**Comment by Masamune3210** [comment]
script works great, grabbed the unencrypted files!
