### ISSUE TITLE
CUSA01665 Dead or Alive Last Round - syntax error

### ISSUE THREAD

**Issue by Masamune3210** [hippie68/ftpdump#23]
Trying to dump CUSA01665, around 65% it spat this out as the directory listing
![image](https://user-images.githubusercontent.com/1053504/187473695-14827e47-c4bf-402f-9f0f-4ecb0303a5a0.png)

and started erroring out because Im assuming the filenames are invalid
![image](https://user-images.githubusercontent.com/1053504/187473882-5abb3ccc-48ee-46af-abfc-4899fd845bb5.png)

FileZilla shows the filenames as well, so I don't know if they are the correct filenames or if its a possible bug in the FTP server
![image](https://user-images.githubusercontent.com/1053504/187474413-32e0c838-38a2-4a4f-91cf-537e8d0820f3.png)

**Comment by hippie68** [comment]
Thanks for reporting. This has been fixed in the latest update. It did not affect the files themselves, so the dump should be correct and there's no need to dump again.
The file names are probably correct. Some games have really weird file names.

**Comment by Masamune3210** [comment]
ok, thanks for the program, it works wonderfully so I try to report anything that might be a issue, glad to see its fixed
