### ISSUE TITLE
script seems to be dumping encrypted nptitle.dat?

### ISSUE THREAD

**Issue by dzastsed** [hippie68/ftpdump#25]
as name says, trying to dump battlefield v beta, but nptitle seems to be encrypted. using your FTP payload and edited script to use port 1337
full output: 
*moved to 2nd comment*

**Comment by dzastsed** [comment]
crap that didnt format very well, attempt #2 

> ./ftpdump 11.100.1.8 -p -r --debug
> DEBUG: Bash version "5.1.16(1)-release" detected.
> DEBUG: Could not find optional program "sfo".
> DEBUG: GNU dd detected - using GNU-specific dd options.
> DEBUG: Using current directory as output directory.
> DEBUG: Options: option_app=, option_patch=1, option_dlc=, dump_keystone=, dump_sflash=, dump_appdb=, dump_path=, dump_title_id=, option_no_decrypt=, debug=1, debug_pfs=, curl_options=, curl_verbose=, wget_options=, wget_verbose=, pfs_extraction_enabled=, sfo_path=
> DEBUG: Using FTP server "ftp://11.100.1.8:1337".
> DEBUG: Checking FTP connection ...
> DEBUG: Enabling server-side SELF decryption ...
> DEBUG: SELF decryption enabled.
> DEBUG: Checking if patch data exists.
> Dumping CUSA06593 patch data (16618 MB):
> DEBUG: Dumping directory "/mnt/sandbox/pfsmnt/CUSA06593-patch0/", cutting 4 directories.
> DataPS4.forge
> DataPS4_STP_WhiteRoom.forge
> DataPS4_extra.forge
> DataPS4_extra_chr_onboarding.forge
> PS4Alpes_terrainlin0.tbf
> PS4Alpes_terrainlin1.tbf
> eboot.bin
> libshadercontainer_engine_orbis_f.prx
> localization.lang
> sce_discmap.plt
> sce_discmap_patch.plt
> session_image.jpg
> session_image_200.jpg
> streaminginstall.ini
> savecontent/
> savecontent/icon0_ps4.png
> sce_module/
> sce_module/libSceFios2.prx
> sce_module/libSceNpToolkit.prx
> sce_module/libc.prx
> sce_sys/
> sce_sys/about/
> sce_sys/about/right.sprx
> sce_sys/changeinfo/
> sounddata/
> sounddata/ps4/
> sounddata/ps4/sounds_eng.pck
> sounddata/ps4/sounds_fre.pck
> sounddata/ps4/sounds_ger.pck
> sounddata/ps4/sounds_ita.pck
> sounddata/ps4/sounds_sfx.pck
> sounddata/ps4/sounds_spa.pck
> videos/
> videos/AIR_BALLOON_01_Aravis.bk2
> videos/AIR_BALLOON_04_Tyrol.bk2
> videos/INVITATIONAL_01.bk2
> videos/INVITATIONAL_02.bk2
> videos/INVITATIONAL_03.bk2
> videos/INVITATIONAL_04.bk2
> videos/INVITATIONAL_05.bk2
> videos/INVITATIONAL_06.bk2
> videos/INVITATIONAL_07.bk2
> videos/INVITATIONAL_08.bk2
> videos/LDZ_ARAVIS_01.bk2
> videos/STP_ALP_ONBOARDING.bk2
> videos/STP_ALP_ONBOARDING_WRAPUP.bk2
> videos/STP_ALP_OnboardingTricks.bk2
> videos/TYROL_LDZ_01.bk2
> videos/loading_logo.bk2
> videos/start_menu.bk2
> videos/de/
> videos/de/disclaimer.bk2
> videos/en/
> videos/en/disclaimer.bk2
> videos/es/
> videos/es/disclaimer.bk2
> videos/fr/
> videos/fr/disclaimer.bk2
> videos/it/
> videos/it/disclaimer.bk2
> 35% Wget reported error 139: "Unknown error (see https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html."
> Error encountered, script aborted.
> dzastsedf@DESKTOP-3HS2GQB:~/ftpdump$ ./ftpdump 11.100.1.8 -p -a -k -r --debug
> DEBUG: Bash version "5.1.16(1)-release" detected.
> DEBUG: Could not find optional program "sfo".
> DEBUG: GNU dd detected - using GNU-specific dd options.
> DEBUG: Using current directory as output directory.
> DEBUG: Options: option_app=1, option_patch=1, option_dlc=, dump_keystone=1, dump_sflash=, dump_appdb=, dump_path=, dump_title_id=, option_no_decrypt=, debug=1, debug_pfs=, curl_options=, curl_verbose=, wget_options=, wget_verbose=, pfs_extraction_enabled=, sfo_path=
> DEBUG: Using FTP server "ftp://11.100.1.8:1337".
> DEBUG: Checking FTP connection ...
> DEBUG: Enabling server-side SELF decryption ...
> DEBUG: SELF decryption enabled.
> Dumping CUSA13212 keystone:
> keystone
> Dumping CUSA13212 app data (11456 MB):
> DEBUG: Dumping directory "/mnt/sandbox/pfsmnt/CUSA13212-app0/", cutting 4 directories.
> EAWebKit.prx
> Engine.BuildInfo_gen4b_retail.prx
> Extension.Twinkle.Codec_gen4b_retail.prx
> Extension.Twinkle.JavaScriptCore_gen4b_retail.prx
> eboot.bin
> package.mft
> saveicon.png
> sce_discmap.plt
> Data/
> Data/chunkmanifest
> Data/initfs_Gen4b
> Data/layout.toc
> Data/Gen4b/
> Data/Gen4b/installation/
> Data/Gen4b/installation/openbeta/
> Data/Gen4b/installation/openbeta/openbetainstallpkg/
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas.cat
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_01.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_02.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_03.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_04.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_05.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_06.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_07.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_08.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_09.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_10.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_11.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_12.cas
> sce_module/
> sce_module/libSceFace.prx
> sce_module/libSceFios2.prx
> sce_module/libSceHand.prx
> sce_module/libSceS3DConversion.prx
> sce_module/libSceSmart.prx
> sce_module/libc.prx
> sce_sys/
> sce_sys/keystone
> sce_sys/about/
> sce_sys/about/right.sprx
> Preparing extraction of app.pkg ...
> DEBUG: Dumping 48 bytes from app.pkg to get body size.
> DEBUG: Body offset: 8192
> DEBUG: Body size: 11526144
> DEBUG: Dumping body from app.pkg (11534336 bytes).
> DEBUG: Extracting ...
> DEBUG: ID: 0x1
> DEBUG: File name offset: 0
> DEBUG: Data offset: 11712
> DEBUG: Size: 832
> DEBUG: ID: 0x10
> DEBUG: File name offset: 0
> DEBUG: Data offset: 8192
> DEBUG: Size: 2048
> DEBUG: ID: 0x20
> DEBUG: File name offset: 0
> DEBUG: Data offset: 10240
> DEBUG: Size: 256
> DEBUG: ID: 0x80
> DEBUG: File name offset: 0
> DEBUG: Data offset: 10496
> DEBUG: Size: 384
> DEBUG: ID: 0x100
> DEBUG: File name offset: 0
> DEBUG: Data offset: 10880
> DEBUG: Size: 832
> DEBUG: ID: 0x200
> DEBUG: File name offset: 0
> DEBUG: Data offset: 12544
> DEBUG: Size: 208
> DEBUG: ID: 0x400
> DEBUG: File name offset: 0
> DEBUG: Data offset: 714256
> DEBUG: Size: 1024
> DEBUG: File name: "license.dat"
> Extracting license.dat
> DEBUG: ID: 0x401
> DEBUG: File name offset: 0
> DEBUG: Data offset: 715280
> DEBUG: Size: 512
> DEBUG: File name: "license.info"
> Extracting license.info
> DEBUG: ID: 0x402
> DEBUG: File name offset: 0
> DEBUG: Data offset: 11059536
> DEBUG: Size: 160
> DEBUG: File name: "nptitle.dat"
> Extracting nptitle.dat
> DEBUG: ID: 0x409
> DEBUG: File name offset: 0
> DEBUG: Data offset: 11059696
> DEBUG: Size: 8192
> DEBUG: File name: "psreserved.dat"
> Extracting psreserved.dat
> DEBUG: ID: 0x1000
> DEBUG: File name offset: 1
> DEBUG: Data offset: 715792
> DEBUG: Size: 1884
> DEBUG: File name: "param.sfo"
> Extracting param.sfo
> DEBUG: ID: 0x1001
> DEBUG: File name offset: 11
> DEBUG: Data offset: 12752
> DEBUG: Size: 688
> DEBUG: File name: "playgo-chunk.dat"
> Extracting playgo-chunk.dat
> DEBUG: ID: 0x1002
> DEBUG: File name offset: 28
> DEBUG: Data offset: 13440
> DEBUG: Size: 700420
> DEBUG: File name: "playgo-chunk.sha"
> Extracting playgo-chunk.sha
> DEBUG: ID: 0x1003
> DEBUG: File name offset: 45
> DEBUG: Data offset: 713872
> DEBUG: Size: 370
> DEBUG: File name: "playgo-manifest.xml"
> Extracting playgo-manifest.xml
> DEBUG: ID: 0x1004
> DEBUG: File name offset: 65
> DEBUG: Data offset: 11055424
> DEBUG: Size: 3857
> DEBUG: File name: "pronunciation.xml"
> Extracting pronunciation.xml
> DEBUG: ID: 0x1005
> DEBUG: File name offset: 83
> DEBUG: Data offset: 11059296
> DEBUG: Size: 20
> DEBUG: File name: "pronunciation.sig"
> Extracting pronunciation.sig
> DEBUG: ID: 0x1006
> DEBUG: File name offset: 101
> DEBUG: Data offset: 4106272
> DEBUG: Size: 2587822
> DEBUG: File name: "pic1.png"
> Extracting pic1.png
> DEBUG: ID: 0x100b
> DEBUG: File name offset: 110
> DEBUG: Data offset: 11059328
> DEBUG: Size: 204
> DEBUG: File name: "shareparam.json"
> Extracting shareparam.json
> DEBUG: ID: 0x1200
> DEBUG: File name offset: 126
> DEBUG: Data offset: 717680
> DEBUG: Size: 400378
> DEBUG: File name: "icon0.png"
> Extracting icon0.png
> DEBUG: ID: 0x1202
> DEBUG: File name offset: 136
> DEBUG: Data offset: 1118064
> DEBUG: Size: 400378
> DEBUG: File name: "icon0_01.png"
> Extracting icon0_01.png
> DEBUG: ID: 0x1220
> DEBUG: File name offset: 149
> DEBUG: Data offset: 1518448
> DEBUG: Size: 2587822
> DEBUG: File name: "pic0.png"
> Extracting pic0.png
> DEBUG: ID: 0x1240
> DEBUG: File name offset: 158
> DEBUG: Data offset: 9030352
> DEBUG: Size: 2025060
> DEBUG: File name: "snd0.at9"
> Extracting snd0.at9
> DEBUG: ID: 0x1280
> DEBUG: File name offset: 167
> DEBUG: Data offset: 6694096
> DEBUG: Size: 131200
> DEBUG: File name: "icon0.dds"
> Extracting icon0.dds
> DEBUG: ID: 0x1282
> DEBUG: File name offset: 177
> DEBUG: Data offset: 6825296
> DEBUG: Size: 131200
> DEBUG: File name: "icon0_01.dds"
> Extracting icon0_01.dds
> DEBUG: ID: 0x12a0
> DEBUG: File name offset: 190
> DEBUG: Data offset: 6956496
> DEBUG: Size: 1036928
> DEBUG: File name: "pic0.dds"
> Extracting pic0.dds
> DEBUG: ID: 0x12c0
> DEBUG: File name offset: 199
> DEBUG: Data offset: 7993424
> DEBUG: Size: 1036928
> DEBUG: File name: "pic1.dds"
> Extracting pic1.dds
> DEBUG: Checking if patch data exists.
> Dumping CUSA13212 patch data (3332 MB):
> DEBUG: Dumping directory "/mnt/sandbox/pfsmnt/CUSA13212-patch0/", cutting 4 directories.
> Engine.BuildInfo_gen4b_retail.prx
> eboot.bin
> sce_discmap.plt
> sce_discmap_patch.plt
> Data/
> Data/initfs_Gen4b
> Data/layout.toc
> Data/Gen4b/
> Data/Gen4b/installation/
> Data/Gen4b/installation/openbeta/
> Data/Gen4b/installation/openbeta/openbetainstallpkg/
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas.cat
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_01.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_02.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_03.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_12.cas
> sce_module/
> sce_sys/
> sce_sys/about/
> sce_sys/about/right.sprx
> sce_sys/changeinfo/
> Preparing extraction of patch.pkg ...
> DEBUG: Dumping 48 bytes from patch.pkg to get body size.
> DEBUG: Body offset: 8192
> DEBUG: Body size: 1040384
> DEBUG: Dumping body from patch.pkg (1048576 bytes).
> DEBUG: Extracting ...
> DEBUG: ID: 0x1
> DEBUG: File name offset: 0
> DEBUG: Data offset: 11424
> DEBUG: Size: 480
> DEBUG: ID: 0x10
> DEBUG: File name offset: 0
> DEBUG: Data offset: 8192
> DEBUG: Size: 2048
> DEBUG: ID: 0x20
> DEBUG: File name offset: 0
> DEBUG: Data offset: 10240
> DEBUG: Size: 256
> DEBUG: ID: 0x80
> DEBUG: File name offset: 0
> DEBUG: Data offset: 10496
> DEBUG: Size: 448
> DEBUG: ID: 0x100
> DEBUG: File name offset: 0
> DEBUG: Data offset: 10944
> DEBUG: Size: 480
> DEBUG: ID: 0x200
> DEBUG: File name offset: 0
> DEBUG: Data offset: 11904
> DEBUG: Size: 112
> DEBUG: ID: 0x402
> DEBUG: File name offset: 0
> DEBUG: Data offset: 626928
> DEBUG: Size: 160
> DEBUG: File name: "nptitle.dat"
> Extracting nptitle.dat
> DEBUG: ID: 0x408
> DEBUG: File name offset: 0
> DEBUG: Data offset: 217152
> DEBUG: Size: 407648
> DEBUG: File name: "origin-deltainfo.dat"
> Extracting origin-deltainfo.dat
> DEBUG: ID: 0x409
> DEBUG: File name offset: 0
> DEBUG: Data offset: 627088
> DEBUG: Size: 8192
> DEBUG: File name: "psreserved.dat"
> Extracting psreserved.dat
> DEBUG: ID: 0x1000
> DEBUG: File name offset: 1
> DEBUG: Data offset: 624800
> DEBUG: Size: 1884
> DEBUG: File name: "param.sfo"
> Extracting param.sfo
> DEBUG: ID: 0x1001
> DEBUG: File name offset: 11
> DEBUG: Data offset: 12016
> DEBUG: Size: 688
> DEBUG: File name: "playgo-chunk.dat"
> Extracting playgo-chunk.dat
> DEBUG: ID: 0x1002
> DEBUG: File name offset: 28
> DEBUG: Data offset: 12704
> DEBUG: Size: 203376
> DEBUG: File name: "playgo-chunk.sha"
> Extracting playgo-chunk.sha
> DEBUG: ID: 0x1003
> DEBUG: File name offset: 45
> DEBUG: Data offset: 216080
> DEBUG: Size: 370
> DEBUG: File name: "playgo-manifest.xml"
> Extracting playgo-manifest.xml
> DEBUG: ID: 0x1008
> DEBUG: File name offset: 65
> DEBUG: Data offset: 216464
> DEBUG: Size: 688
> DEBUG: File name: "app/playgo-chunk.dat"
> Extracting app/playgo-chunk.dat
> DEBUG: ID: 0x1260
> DEBUG: File name offset: 86
> DEBUG: Data offset: 626688
> DEBUG: Size: 229
> DEBUG: File name: "changeinfo/changeinfo.xml"
> Extracting changeinfo/changeinfo.xml
> Done.

**Comment by dzastsed** [comment]
yup, just tried a dump with old dumper payload and contents of the file are decrypted. this was done on 7.02 fw if that means anything

**Comment by dzastsed** [comment]
aand tried with another game, for same results

**Comment by hippie68** [comment]
Thanks for reporting.
Please let me know if the attached updated script fixes the problem:

[ftpdump.zip](https://github.com/hippie68/ftpdump/files/12149056/ftpdump.zip)

**Comment by dzastsed** [comment]
fails to dump it completely: 

> dzastsedf@DESKTOP-3HS2GQB:~/ftpdump$ ./ftpdump 11.100.1.8 -p --debug
> DEBUG: Bash version "5.1.16(1)-release" detected.
> DEBUG: Could not find optional program "sfo".
> DEBUG: GNU dd detected - using GNU-specific dd options.
> DEBUG: Using current directory as output directory.
> DEBUG: Options: option_app=, option_patch=1, option_dlc=, dump_keystone=, dump_sflash=, dump_appdb=, dump_path=, dump_title_id=, option_no_decrypt=, debug=1, debug_pfs=, curl_options=, curl_verbose=, wget_options=, wget_verbose=, pfs_extraction_enabled=, sfo_path=
> DEBUG: Using FTP server "ftp://11.100.1.8:1337".
> DEBUG: Checking FTP connection ...
> DEBUG: Enabling server-side SELF decryption ...
> DEBUG: SELF decryption enabled.
> DEBUG: Checking if patch data exists.
> Dumping CUSA13212 patch data (3332 MB):
> DEBUG: Dumping directory "/mnt/sandbox/pfsmnt/CUSA13212-patch0/", cutting 4 directories.
> Engine.BuildInfo_gen4b_retail.prx
> eboot.bin
> sce_discmap.plt
> sce_discmap_patch.plt
> Data/
> Data/initfs_Gen4b
> Data/layout.toc
> Data/Gen4b/
> Data/Gen4b/installation/
> Data/Gen4b/installation/openbeta/
> Data/Gen4b/installation/openbeta/openbetainstallpkg/
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas.cat
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_01.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_02.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_03.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_12.cas
> sce_module/
> sce_sys/
> sce_sys/about/
> sce_sys/about/right.sprx
> sce_sys/changeinfo/
> Preparing extraction of patch.pkg ...
> DEBUG: Dumping 48 bytes from patch.pkg to get body size.
> DEBUG: Body offset: 8192
> DEBUG: Body size: 1040384
> DEBUG: Dumping body from patch.pkg (1048576 bytes).
> DEBUG: Extracting ...
> DEBUG: ID: 0x1
> DEBUG: File name offset: 0
> DEBUG: Data offset: 11424
> DEBUG: Size: 480
> DEBUG: ID: 0x10
> DEBUG: File name offset: 0
> DEBUG: Data offset: 8192
> DEBUG: Size: 2048
> DEBUG: ID: 0x20
> DEBUG: File name offset: 0
> DEBUG: Data offset: 10240
> DEBUG: Size: 256
> DEBUG: ID: 0x80
> DEBUG: File name offset: 0
> DEBUG: Data offset: 10496
> DEBUG: Size: 448
> DEBUG: ID: 0x100
> DEBUG: File name offset: 0
> DEBUG: Data offset: 10944
> DEBUG: Size: 480
> DEBUG: ID: 0x200
> DEBUG: File name offset: 0
> DEBUG: Data offset: 11904
> DEBUG: Size: 112
> DEBUG: ID: 0x402
> DEBUG: File name offset: 0
> DEBUG: Data offset: 626928
> DEBUG: Size: 160
> DEBUG: File name: "nptitle.dat"
> Extracting nptitle.dat
> DEBUG: ID: 0x408
> DEBUG: File name offset: 0
> DEBUG: Data offset: 217152
> DEBUG: Size: 407648
> DEBUG: File name: "origin-deltainfo.dat"
> Extracting origin-deltainfo.dat
> DEBUG: ID: 0x409
> DEBUG: File name offset: 0
> DEBUG: Data offset: 627088
> DEBUG: Size: 8192
> DEBUG: File name: "psreserved.dat"
> Extracting psreserved.dat
> DEBUG: ID: 0x1000
> DEBUG: File name offset: 1
> DEBUG: Data offset: 624800
> DEBUG: Size: 1884
> DEBUG: File name: "param.sfo"
> Extracting param.sfo
> DEBUG: ID: 0x1001
> DEBUG: File name offset: 11
> DEBUG: Data offset: 12016
> DEBUG: Size: 688
> DEBUG: File name: "playgo-chunk.dat"
> Extracting playgo-chunk.dat
> DEBUG: ID: 0x1002
> DEBUG: File name offset: 28
> DEBUG: Data offset: 12704
> DEBUG: Size: 203376
> DEBUG: File name: "playgo-chunk.sha"
> Extracting playgo-chunk.sha
> DEBUG: ID: 0x1003
> DEBUG: File name offset: 45
> DEBUG: Data offset: 216080
> DEBUG: Size: 370
> DEBUG: File name: "playgo-manifest.xml"
> Extracting playgo-manifest.xml
> DEBUG: ID: 0x1008
> DEBUG: File name offset: 65
> DEBUG: Data offset: 216464
> DEBUG: Size: 688
> DEBUG: File name: "app/playgo-chunk.dat"
> Extracting app/playgo-chunk.dat
> DEBUG: ID: 0x1260
> DEBUG: File name offset: 86
> DEBUG: Data offset: 626688
> DEBUG: Size: 229
> DEBUG: File name: "changeinfo/changeinfo.xml"
> Extracting changeinfo/changeinfo.xml
> Replacing npbind.dat and nptitle.dat ...
> No such file 'npbind.dat'.
> DEBUG: Download failed - removing empty file "npbind.dat".
> Wget reported error 8: "Server issued an error response."
> Error encountered, script aborted.
> dzastsedf@DESKTOP-3HS2GQB:~/ftpdump$

**Comment by dzastsed** [comment]
*for the record this happens with base too; just didnt have debug output set*

> 
> dzastsedf@DESKTOP-3HS2GQB:~/ftpdump$ ./ftpdump 11.100.1.8
> Dumping CUSA13212 app data (11456 MB):
> EAWebKit.prx
> Engine.BuildInfo_gen4b_retail.prx
> Extension.Twinkle.Codec_gen4b_retail.prx
> Extension.Twinkle.JavaScriptCore_gen4b_retail.prx
> eboot.bin
> package.mft
> saveicon.png
> sce_discmap.plt
> Data/
> Data/chunkmanifest
> Data/initfs_Gen4b
> Data/layout.toc
> Data/Gen4b/
> Data/Gen4b/installation/
> Data/Gen4b/installation/openbeta/
> Data/Gen4b/installation/openbeta/openbetainstallpkg/
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas.cat
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_01.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_02.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_03.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_04.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_05.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_06.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_07.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_08.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_09.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_10.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_11.cas
> Data/Gen4b/installation/openbeta/openbetainstallpkg/cas_12.cas
> sce_module/
> sce_module/libSceFace.prx
> sce_module/libSceFios2.prx
> sce_module/libSceHand.prx
> sce_module/libSceS3DConversion.prx
> sce_module/libSceSmart.prx
> sce_module/libc.prx
> sce_sys/
> sce_sys/keystone
> sce_sys/about/
> sce_sys/about/right.sprx
> Preparing extraction of app.pkg ...
> Extracting license.dat
> Extracting license.info
> Extracting nptitle.dat
> Extracting psreserved.dat
> Extracting param.sfo
> Extracting playgo-chunk.dat
> Extracting playgo-chunk.sha
> Extracting playgo-manifest.xml
> Extracting pronunciation.xml
> Extracting pronunciation.sig
> Extracting pic1.png
> Extracting shareparam.json
> Extracting icon0.png
> Extracting icon0_01.png
> Extracting pic0.png
> Extracting snd0.at9
> Extracting icon0.dds
> Extracting icon0_01.dds
> Extracting pic0.dds
> Extracting pic1.dds
> Replacing npbind.dat and nptitle.dat ...
> No such file 'npbind.dat'.
> Wget reported error 8: "Server issued an error response."
> Error encountered, script aborted.

**Comment by hippie68** [comment]
This should hopefully do the trick:
[ftpdump.zip](https://github.com/hippie68/ftpdump/files/12150252/ftpdump.zip)

**Comment by dzastsed** [comment]
hi, sorry for late reply, github didnt send a notification to email. yes, this update does indeed dump decrypted nptitle now! thanks!
