### ISSUE TITLE
 dump tool will create empty npbind.dat and nptitle.dat when dumping some pkg's like Disney + and mini soundtracks.

### ISSUE THREAD

**Issue by codemasterv** [hippie68/ftpdump#7]
The dump tool will create empty npbind.dat and nptitle.dat when dumping some pkg's like Disney + and mini soundtracks.

PubGen will throw errors because these files are empty. Once removed from sce_sys the pkg will build without errors

**Comment by hippie68** [comment]
Thank you for reporting. It should be fixed now.
